WIP: Begin
LTD-Beget/ftp pull request #1
Opened 2018-03-23 10:38 UTC by Valkeru

2018-03-23 13:44 UTC, Grey2k commented on proto/v1/ftp.proto
> +
Лучше сделать не Toggle а setSshAccess  (enabled/disabled) иденпотентно и чтобы он возвращал статус конечный

2018-03-23 13:44 UTC, Grey2k commented on proto/v1/ftp.proto
> +message SetPasswordRequest {
ChangePassword привычнее

2018-03-23 13:44 UTC, Grey2k commented on proto/v1/ftp.proto
> +message GetSiteListResponse {
Это не имеет отношения к FTP

2018-03-23 13:44 UTC, Grey2k commented on proto/v1/ftp.proto
> +message getAccountListRequest {
FindAll , FindOne - как в других API

2018-03-23 13:44 UTC, Grey2k commented on proto/v1/ftp.proto
> +message AddAccountRequest {
CreateAccount

2018-03-23 13:44 UTC, Grey2k commented on proto/v1/ftp.proto
> +    message Success {
Ошибки

2018-03-23 13:44 UTC, Grey2k commented on proto/v1/structures.proto
> +    string homedir = 2;
SSH

2018-03-23 13:44 UTC, Grey2k commented on proto/v1/ftp.proto
> +        option: (google.api.http) = {
POST

2018-03-26 12:45 UTC, Grey2k requested changes

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +    structures.FtpAccount ftp_account = 1;
Ошибки

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +    string password = 2;
Ошибки

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +    uint32 suffix = 1;
Ошибки

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +        UNAVAILABLE = 2;
Надо под методы

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/structures.proto
> +    string login = 1;
home_path

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/structures.proto
> +    string login = 1;
id

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +    rpc findAll (FindAllRequest) returns (FindAllResponse) {
Домавить комментарии

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +        repeated structures.FtpAccount ftp_account = 1;
можно убрать oneof

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +message Error {
Лучше определить для каждого метода свой формат ошибок

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +        uint32 id = 1;
здесь suffix нет , у тебя по id только доступно

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +        string message = 1;
а где code ?

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +    oneof condition {
только id

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +        uint32 id = 1;
только id

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +            UNAVAILABLE_FOR_FREE_HOSTING = 1;
NOT_AVALIBLE  (пояснения можно в  message отправить)

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/structures.proto
> +    bool ssh_enabled = 4;
ssh_status

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +        uint32 id = 1;
только id

2018-03-26 12:45 UTC, Grey2k commented on proto/v1/ftp.proto
> +            TOO_SHORT_PASSWORD = 1;
лучше наоборот 
```
PASSWORD_TOO_SHORT
PASSWORD_TOO_WAEK
```

Когда произойдет INCORRECT_PASSWORD ?

2018-03-26 13:01 UTC, Valkeru commented on proto/v1/ftp.proto
> +            TOO_SHORT_PASSWORD = 1;
Например, при ошибке валидации, если юзер туда засунет кириллицу.

2018-03-26 15:02 UTC, Grey2k commented on proto/v1/ftp.proto
> +    rpc enableSsh (SetSshAccessEnabledRequest) returns (SetSshAccessEnabledResponse) {
EnableRequest

2018-03-26 15:03 UTC, Grey2k approved these changes

2018-03-26 15:03 UTC, merged